# Generated by Django 5.1.6 on 2025-04-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=300)),
                ('popis', models.TextField(blank=True, default='')),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='produkty/')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barva', models.CharField(blank=True, max_length=100)),
                ('velikost', models.CharField(blank=True, max_length=50)),
                ('recenze', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='VKosiku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=300)),
                ('rok', models.IntegerField(blank=True, null=True)),
                ('popis', models.TextField(blank=True, default='')),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.produkt')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
