# Generated by Django 5.1.6 on 2025-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='recenze',
        ),
        migrations.AddField(
            model_name='produkt',
            name='kategorie',
            field=models.CharField(choices=[('detske', 'Dětské'), ('damske', 'Dámské'), ('panske', 'Pánské')], default='detske', max_length=10),
        ),
    ]
