# Generated by Django 5.1.6 on 2025-05-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_produkt_recenze_produkt_kategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkosiku',
            name='popis',
        ),
        migrations.RemoveField(
            model_name='vkosiku',
            name='rok',
        ),
        migrations.AlterField(
            model_name='vkosiku',
            name='jmeno',
            field=models.CharField(blank=True, default='Košík', max_length=300),
        ),
        migrations.AlterField(
            model_name='vkosiku',
            name='produkt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.produkt'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('produkty', models.ManyToManyField(to='main.produkt')),
            ],
        ),
    ]
